import { StyleSheet } from 'react-native';

export const THEME = {
  background: '#FBF8F1',
  surface: '#FFFFFF',
  ink: '#252421',
  muted: '#716E67',
  line: '#E8E1D6',
  yellow: '#F4D36A',
  yellowDark: '#7C671E',
  coral: '#D77969',
};

export const shadow = {
  shadowColor: '#6D604A',
  shadowOffset: { width: 0, height: 4 },
  shadowOpacity: 0.12,
  shadowRadius: 10,
  elevation: 3,
};

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: THEME.background },
  screen: { flex: 1 },
  loadingScreen: { flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: THEME.background },
  loadingText: { marginTop: 12, color: THEME.muted, fontSize: 14 },
  scrollContent: { paddingHorizontal: 20, paddingTop: 14, paddingBottom: 110 },
  brandHeader: { alignItems: 'center', marginBottom: 18 },
  brand: { color: THEME.ink, fontSize: 36, fontWeight: '800', letterSpacing: -2 },
  brandTagline: { color: THEME.yellowDark, fontSize: 10, fontWeight: '700', letterSpacing: 2.2, marginTop: 2 },
  segment: { alignSelf: 'center', backgroundColor: '#EDE9E1', borderRadius: 22, flexDirection: 'row', padding: 4 },
  segmentButton: { borderRadius: 18, paddingHorizontal: 26, paddingVertical: 9 },
  segmentButtonActive: { backgroundColor: THEME.surface, ...shadow },
  segmentText: { color: THEME.muted, fontSize: 14, fontWeight: '600' },
  segmentTextActive: { color: THEME.ink },
  codeCard: { backgroundColor: THEME.surface, borderColor: THEME.line, borderRadius: 20, borderWidth: 1, marginTop: 16, padding: 16, ...shadow },
  eyebrow: { color: THEME.yellowDark, fontSize: 11, fontWeight: '800', letterSpacing: 1.2 },
  codeHint: { color: THEME.muted, fontSize: 12, marginTop: 4 },
  codeRow: { marginTop: 12 },
  codeInput: { backgroundColor: THEME.background, borderColor: THEME.line, borderRadius: 12, borderWidth: 1, color: THEME.ink, flex: 1, fontSize: 18, fontWeight: '800', letterSpacing: 3, paddingHorizontal: 14, paddingVertical: 10 },
  codeLength: { color: THEME.muted, fontSize: 11, marginTop: 4, textAlign: 'right' },
  codeActions: { flexDirection: 'row', gap: 10, justifyContent: 'flex-end', marginTop: 8 },
  sectionTitle: { color: THEME.ink, fontSize: 24, fontWeight: '800', marginTop: 24, textAlign: 'center' },
  sectionSubtitle: { color: THEME.muted, fontSize: 13, marginBottom: 16, marginTop: 5, textAlign: 'center' },
  machineShell: { backgroundColor: '#FFF3C8', borderColor: '#E4CF8C', borderRadius: 28, borderWidth: 2, padding: 12, ...shadow },
  machineLabel: { alignItems: 'center', paddingBottom: 10 },
  machineLabelText: { color: '#6F5B20', fontSize: 10, fontWeight: '800', letterSpacing: 1.2 },
  reelWindow: { alignItems: 'stretch', backgroundColor: '#D8CDB4', borderColor: '#B5A27B', borderRadius: 18, borderWidth: 5, flexDirection: 'row', height: 190, justifyContent: 'center', overflow: 'hidden', padding: 7, position: 'relative' },
  reel: { borderColor: 'rgba(255,255,255,0.35)', borderWidth: 1, flex: 1 },
  selector: { alignItems: 'center', backgroundColor: '#F9F6EE', borderColor: '#D6CDB9', borderRadius: 15, borderWidth: 2, height: 82, justifyContent: 'center', left: '39%', padding: 9, position: 'absolute', top: 50, width: '22%', ...shadow },
  selectorColor: { borderColor: '#D7CCB6', borderRadius: 8, borderWidth: 1, height: '100%', width: '100%' },
  machineControls: { alignItems: 'center', flexDirection: 'row', height: 50, paddingHorizontal: 8, paddingTop: 10 },
  smallLight: { backgroundColor: '#E99B8F', borderColor: '#A76C62', borderRadius: 8, borderWidth: 1, height: 16, marginRight: 8, width: 16 },
  speaker: { gap: 4, marginLeft: 10 },
  speakerLine: { backgroundColor: '#9E8954', borderRadius: 2, height: 3, width: 44 },
  dial: { backgroundColor: '#F7F2E8', borderColor: '#A99565', borderRadius: 18, borderWidth: 2, height: 36, marginLeft: 'auto', width: 36 },
  resultCard: { alignItems: 'center', backgroundColor: THEME.surface, borderColor: THEME.line, borderRadius: 22, borderWidth: 1, flexDirection: 'row', marginTop: 16, padding: 16, ...shadow },
  largeSwatch: { borderRadius: 18, height: 92, width: 92 },
  resultCopy: { flex: 1, marginLeft: 16 },
  colorName: { color: THEME.ink, fontSize: 25, fontWeight: '800', marginTop: 4 },
  colorMood: { color: THEME.muted, fontSize: 13, lineHeight: 19, marginTop: 4 },
  primaryButton: { alignItems: 'center', backgroundColor: THEME.yellow, borderColor: '#DDBA4E', borderRadius: 16, borderWidth: 1, justifyContent: 'center', marginTop: 16, minHeight: 54, paddingHorizontal: 18, ...shadow },
  primaryButtonText: { color: THEME.ink, fontSize: 16, fontWeight: '800' },
  disabledButton: { opacity: 0.42 },
  smallButton: { alignItems: 'center', backgroundColor: THEME.surface, borderColor: THEME.line, borderRadius: 12, borderWidth: 1, justifyContent: 'center', minHeight: 44, paddingHorizontal: 14 },
  smallButtonText: { color: THEME.ink, fontSize: 13, fontWeight: '700' },
  captureContent: { paddingHorizontal: 20, paddingTop: 8, paddingBottom: 42 },
  screenHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', marginBottom: 12 },
  backButton: { alignItems: 'center', height: 44, justifyContent: 'center', width: 44 },
  backButtonText: { color: THEME.ink, fontSize: 36, lineHeight: 38 },
  screenHeaderTitle: { color: THEME.ink, fontSize: 20, fontWeight: '800' },
  headerSpacer: { width: 44 },
  captureGuide: { color: THEME.muted, fontSize: 14, marginBottom: 16, textAlign: 'center' },
  photoFrame: { aspectRatio: 4 / 5, backgroundColor: '#EFEAE1', borderColor: THEME.line, borderRadius: 24, borderWidth: 1, overflow: 'hidden', ...shadow },
  capturePhotoRow: { flexDirection: 'row', gap: 10 },
  photoColumn: { flex: 1 },
  photo: { height: '100%', width: '100%' },
  zoomTouch: { flex: 1 },
  zoomBackdrop: { alignItems: 'center', backgroundColor: 'rgba(0,0,0,0.92)', flex: 1, justifyContent: 'center' },
  zoomImage: { height: '100%', width: '100%' },
  photoPlaceholder: { alignItems: 'center', flex: 1, justifyContent: 'center' },
  photoPlaceholderMark: { color: '#A79E91', fontSize: 42, fontWeight: '200' },
  photoPlaceholderText: { color: THEME.muted, fontSize: 14, fontWeight: '700', marginTop: 8 },
  actionRow: { flexDirection: 'row', gap: 10, justifyContent: 'center', marginTop: 14 },
  localOnly: { color: THEME.muted, fontSize: 11, lineHeight: 17, marginTop: 12, textAlign: 'center' },
  shareContent: { alignItems: 'stretch', paddingHorizontal: 20, paddingTop: 8, paddingBottom: 42 },
  shareCard: { aspectRatio: 4 / 5, backgroundColor: '#FFF9E9', borderColor: '#D9C998', borderRadius: 22, borderWidth: 1, overflow: 'hidden', padding: 20 },
  shareBrandRow: { alignItems: 'baseline', flexDirection: 'row', justifyContent: 'space-between' },
  shareBrand: { color: THEME.ink, fontSize: 28, fontWeight: '900', letterSpacing: -1.5 },
  shareDate: { color: THEME.muted, fontSize: 11, fontWeight: '600' },
  soloPhoto: { flex: 1, marginVertical: 14, overflow: 'hidden' },
  friendPhotos: { flex: 1, flexDirection: 'row', gap: 7, marginVertical: 14, overflow: 'hidden' },
  sharePhoto: { borderRadius: 14, flex: 1, height: '100%', resizeMode: 'cover' },
  shareResultRow: { alignItems: 'center', flexDirection: 'row' },
  shareSwatch: { borderRadius: 14, height: 56, width: 56 },
  shareResultCopy: { marginLeft: 12 },
  shareEyebrow: { color: THEME.yellowDark, fontSize: 9, fontWeight: '900', letterSpacing: 1.3 },
  shareColorName: { color: THEME.ink, fontSize: 22, fontWeight: '900', marginTop: 2 },
  shareQuestion: { color: THEME.ink, fontSize: 15, fontWeight: '800', marginTop: 14, textAlign: 'center' },
  shareCode: { color: THEME.muted, fontSize: 9, fontWeight: '700', letterSpacing: 1.4, marginTop: 7, textAlign: 'center' },
  secondaryButton: { alignItems: 'center', borderColor: THEME.line, borderRadius: 16, borderWidth: 1, justifyContent: 'center', marginTop: 10, minHeight: 50 },
  secondaryButtonText: { color: THEME.ink, fontSize: 14, fontWeight: '700' },
  historyContent: { paddingHorizontal: 20, paddingTop: 14, paddingBottom: 120 },
  plusCard: { backgroundColor: '#FFF3C8', borderColor: '#E4CF8C', borderRadius: 20, borderWidth: 1, marginTop: 16, padding: 18, ...shadow },
  plusEyebrow: { color: THEME.yellowDark, fontSize: 11, fontWeight: '800', letterSpacing: 1.2 },
  plusTitle: { color: THEME.ink, fontSize: 18, fontWeight: '800', marginTop: 6 },
  plusText: { color: THEME.muted, fontSize: 13, lineHeight: 19, marginTop: 6 },
  plusButton: { alignItems: 'center', backgroundColor: THEME.yellow, borderRadius: 14, marginTop: 14, minHeight: 46, justifyContent: 'center', paddingHorizontal: 16 },
  plusButtonText: { color: THEME.ink, fontSize: 15, fontWeight: '800' },
  restoreText: { color: THEME.yellowDark, fontSize: 13, fontWeight: '700', marginTop: 13, textAlign: 'center', textDecorationLine: 'underline' },
  emptyCard: { alignItems: 'center', backgroundColor: THEME.surface, borderColor: THEME.line, borderRadius: 20, borderWidth: 1, marginTop: 18, padding: 28 },
  emptyTitle: { color: THEME.ink, fontSize: 16, fontWeight: '800' },
  emptyText: { color: THEME.muted, fontSize: 13, marginTop: 7, textAlign: 'center' },
  historyCard: { backgroundColor: THEME.surface, borderColor: THEME.line, borderRadius: 18, borderWidth: 1, marginTop: 12, overflow: 'hidden', ...shadow },
  historyMain: { alignItems: 'center', flexDirection: 'row', padding: 12 },
  historyImage: { borderRadius: 12, height: 70, width: 56 },
  historyCopy: { flex: 1, marginLeft: 12 },
  historyDate: { color: THEME.muted, fontSize: 11 },
  historyColor: { color: THEME.ink, fontSize: 17, fontWeight: '800', marginTop: 3 },
  historyMode: { color: THEME.muted, fontSize: 12, marginTop: 2 },
  historySwatch: { borderRadius: 12, height: 42, width: 42 },
  deleteButton: { alignItems: 'center', borderTopColor: THEME.line, borderTopWidth: 1, paddingVertical: 10 },
  deleteButtonText: { color: '#A1493E', fontSize: 12, fontWeight: '700' },
  privacyCard: { backgroundColor: '#F2EEE5', borderRadius: 18, marginTop: 24, padding: 18 },
  privacyTitle: { color: THEME.ink, fontSize: 16, fontWeight: '800' },
  privacyText: { color: THEME.muted, fontSize: 12, lineHeight: 19, marginTop: 7 },
  deleteAllButton: { alignItems: 'center', borderColor: '#D9B7B0', borderRadius: 12, borderWidth: 1, marginTop: 14, padding: 11 },
  deleteAllText: { color: '#983F34', fontSize: 12, fontWeight: '800' },
  bottomNav: { backgroundColor: 'rgba(255,255,255,0.97)', borderTopColor: THEME.line, borderTopWidth: 1, bottom: 0, flexDirection: 'row', left: 0, paddingTop: 8, position: 'absolute', right: 0 },
  navItem: { alignItems: 'center', flex: 1, minHeight: 48 },
  navMark: { color: THEME.muted, fontSize: 23, lineHeight: 26 },
  navLabel: { color: THEME.muted, fontSize: 11, marginTop: 2 },
  navActive: { color: THEME.yellowDark, fontWeight: '800' },
});

